Repository cycloidio/terracognita, pull requests merged in 2019-12, with the labels that each got.

#68 Added: AWS 'launch_configuration', 'launch_template' and 'autoscaling_group' resources
  CHANGELOG.md
  aws/resources.go
  aws/resourcetype_enumer.go
  go.mod
  provider/import.go
  provider/import_test.go
Labels: Status: Need review, Type: Enhancement

#73 add several components
  google/cmd/generate.go
  google/cmd/template.go
  google/reader.go
  google/reader_generated.go
  google/resources.go
  google/resourcetype_enumer.go
Labels: Provider: GCP, Status: Need review, Type: Enhancement

#71 Changed: 'raws' to be an internal library and not a dependency
  CHANGELOG.md
  CONTRIBUTING.md
  aws/cmd/functions.go
  aws/cmd/main.go
  aws/cmd/main_test.go
  aws/cmd/template.go
  aws/cmd/template_test.go
  aws/cmd/testdata/generated.go
  aws/provider.go
  aws/reader/connector.go
  aws/reader/list_buckets.go
  aws/reader/reader.go
  aws/resources.go
  go.mod
  go.sum
Labels: Status: Need review

#75 changelog: add three more google components
  CHANGELOG.md
Labels: Provider: GCP, Status: Need review, Type: Docs

#77 README: Remove last links to 'raws'
  README.md
  aws/cmd/functions.go
Labels: Status: Need review
