Repository cycloidio/terracognita, pull requests merged in 2020-07, with the labels that each got.

#123 Fix: Pagination and nil pointer errors
  CHANGELOG.md
  aws/cmd/functions.go
  aws/cmd/template.go
  aws/cmd/template_test.go
  aws/reader/reader.go
  aws/resources.go
  provider/import.go
Labels: Status: Need review

#125 hcl: avoid mutual interpolation
  CHANGELOG.md
  hcl/writer.go
  hcl/writer_test.go
Labels: Status: Need review, Type: Enhancement

#126 readme: add terracognita blogpost ref
  README.md
Labels: Status: Need review, Type: Docs

#128 aws/resources: aws_alb_listener_certificate aws_lb_cookie_stickiness_policy
  CHANGELOG.md
  aws/cache.go
  aws/cmd/functions.go
  aws/reader/connector.go
  aws/reader/reader.go
  aws/resources.go
  aws/resourcetype_enumer.go
Labels: Status: Need review
