Repository cycloidio/terracognita, pull requests merged in 2020-03, with the labels that each got.

#84 readme: review on `installation` section
  README.md
Labels: Status: Need review

#85 ci: push tag before releasing artifacts
  .ci/pipeline.yml
Labels: Type: Bug

#90 readme: update cycloid link
  README.md
Labels: Type: Docs

#87 aws: new resources
  CHANGELOG.md
  aws/cache.go
  aws/cmd/functions.go
  aws/reader/reader.go
  aws/resources.go
  aws/resourcetype_enumer.go
Labels: Status: Need review, Type: Enhancement

#88 AzureRM provider implementation
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  README.md
  azurerm/cache.go
  azurerm/cmd/generate.go
  azurerm/cmd/template.go
  azurerm/provider.go
  azurerm/reader.go
  azurerm/reader_generated.go
  azurerm/resources.go
  azurerm/resourcetype_enumer.go
  cmd/aws.go
  cmd/azurerm.go
  cmd/azurerm_resources.go
  cmd/google.go
  cmd/root.go
  go.mod
  go.sum
  hcl/writer.go
  provider/resource.go
  state/writer_test.go
Labels: Status: Need review, Type: Enhancement
