Repository cycloidio/terracognita, pull requests merged in 2020-11, with the labels that each got.

#131 tfstate: add dependencies
  CHANGELOG.md
  provider/import.go
  provider/import_test.go
  state/writer.go
  state/writer_test.go
Labels: Status: Need review

#144 ci: add checkout params on pull-request resource
  .ci/pipeline.yml
Labels: Type: Bug

#142 cmd: Add support for AWS Profile/Config
  CHANGELOG.md
  README.md
  cmd/aws.go
Labels: Status: Need review

#143 Changed: Provider and Terraform versions
  CHANGELOG.md
  README.md
  aws/resources.go
  go.mod
  go.sum
  google/provider.go
  hcl/format.go
  hcl/format_test.go
  provider/import_test.go
  state/writer.go
  state/writer_test.go
  tag/tag.go
Labels: Status: Need review

#145 azurerm: add virtual desktops resources
  CHANGELOG.md
  azurerm/cache.go
  azurerm/cmd/generate.go
  azurerm/cmd/template.go
  azurerm/list_virtual_machine_extensions.go
  azurerm/reader_generated.go
  azurerm/resources.go
  azurerm/resourcetype_enumer.go
  go.mod
  go.sum
  mock/writer.go
Labels: Provider: AzureRM, Status: Need review

#147 doc: udpate download to get latest release [skip ci]
  README.md
Labels: Status: Need review, Type: Docs
